### ISSUE TITLE
Support `Texy` in haskintex?

### ISSUE THREAD

**Issue by dmcclean** [Daniel-Diaz/haskintex#4]
(I'm not sure if this is possible, and I haven't tried to make a pull request, because I can't tell exactly what's happening here https://github.com/Daniel-Diaz/haskintex/blob/master/Haskintex.hs#L417-L418.)

It would be cool if `\hatex{ }` commands could include any expression whose type is in the typeclass `Texy`, instead of just `LaTeX`. Basically this would be equivalent to replacing `\hatex{ ... }` with `\hatex{ texy $ ... }` everywhere, but it would make the resulting haskintex documents slightly easier to read.

**Comment by Daniel-Diaz** [comment]
Thanks, this is a good idea!

I think the best approach to this would be to modify the enclosed expression at the parsing phase. It's in this moment when the text is transformed to a Haskell expression, and then converted back to text. So this is the point where we have access to the expression AST and we can apply ``texy`` to it.

What I am not certain about is if this should become the default or be accessed through a flag. At the moment, I will implement it as a flag. If it should become the default behavior, it would do so later, after the feature has been tested enough.

**Comment by dmcclean** [comment]
That's a good point. In principle the change might convert some working documents into errors because of ambiguous types. In practice I think that's unlikely to occur because whatever the top level function is would have to be polymorphic in its result in terms of the `Texy` typeclass and I can't think of anything that is that way. But having this behavior require setting a command-line flag to opt in seems like a perfect solution.

**Comment by Daniel-Diaz** [comment]
I have implemented the new flag `-autotexy`. Could you confirm that it works for you? If so, I will add the correspondent documentation and make a release to Hackage.

**Comment by dmcclean** [comment]
Works for me, thanks very much! If something goes wrong it silently fails leaving that part of the document blank, but I'm not sure if that was the status quo ante.

I have a cool demo that uses this, but it won't be ready for a couple of weeks because I need to tie up some other loose ends to get that working.

One of the loose ends is a HaTeX wrapper for the TeX package `siunitx`. Could I bother you to advise me on how you are supposed to implement commands with two arguments, like `\numrange` (see page 32 of http://mirror.unl.edu/ctan/macros/latex/contrib/siunitx/siunitx.pdf). I see `commS`, `comm0`, and `comm1` and I think I understand them (TeX grammar has always mystified me a bit), but I'm not sure what to do for this one.

**Comment by Daniel-Diaz** [comment]
Use the ˋ-verboseˋ flag and check the messages for errors. This situation might not be ideal, but it is not new in any case. Haskintex runs silently unless ˋ-verboseˋ is given.

As for your two argument command, use ˋliftL2ˋ combined with the data constructors in ˋText.LaTeX.Base.Syntaxˋ. Check other examples in the HaTeX code. There are several tex packages implemented, some of them should be featuring two argument commands. Let me know if you need further advise. I am closing this issue as it is now solved.

**Comment by dmcclean** [comment]
Thanks!
Sorry for the irrelevant question, that was bad form.

**Comment by dmcclean** [comment]
Actually I believe there is a bug here. I had only tested `\hatex{ }` last night and hadn't tested `\iohatex{ }`.

I believe it needs to wrap the expression with `fmap texy $ ...` instead of `texy $ ...` in the `\iohatex{ }` case.

**Comment by dmcclean** [comment]
Or alternatively there could be an

```
instance (Texy a) => Texy (IO a) where
  texy = fmap texy
```

but I think the first solution of changing `haskintex` is probably cleaner since I don't see anything else this instance is good for?

**Comment by Daniel-Diaz** [comment]
That is correct. I don't have time as of this moment. I will look into this tonight if I have time. Thanks for pointing this out.

**Comment by Daniel-Diaz** [comment]
I reopen until `IO` case is taken into account.

**Comment by Daniel-Diaz** [comment]
It turned out it was wrong for `evalhaskell` commands too. I changed the expression processing and it should work for all commands now.

**Comment by Daniel-Diaz** [comment]
I made a release to Hackage. This feature is now available for the public. Let me know if you find further problems.

Thanks.
